Use crawler
relaton/relaton-data-ids pull request #4
Opened 2023-04-28 08:35 UTC by stefanomunarini

2023-04-28 14:03 UTC, andrew2net requested changes

2023-04-28 14:03 UTC, andrew2net commented on crawler.rb
> +
we need to load the source dataset into bibxml-id dir
```sh
rsync -avcizxL rsync.ietf.org::bibxml-ids ./bibxml-id
```

2023-04-29 12:28 UTC, CAMOBAP commented
@stefanomunarini I think this one can be closed in favor of https://github.com/relaton/relaton-data-ids/pull/3

2023-04-29 12:35 UTC, stefanomunarini commented
> @stefanomunarini I think this one can be closed in favor of #3

Right, didn’t see that PR before. Thanks @CAMOBAP

2023-04-29 12:35 UTC, closed without merging