relaton/relaton#110 add deploy workflow
relaton/relaton-data-ids pull request #5
Opened 2023-09-02 22:16 UTC by CAMOBAP

- relaton/relaton#110

2023-09-02 22:26 UTC, CAMOBAP commented
@andrew2net @ronaldtse can you confirm that `GitHub Pages` is enabled for this repository

2023-09-03 03:46 UTC, ronaldtse commented
@CAMOBAP pages is enabled but failing at Jekyll build step

2023-09-03 07:09 UTC, CAMOBAP commented
@andrew2net @ronaldtse here and in https://github.com/relaton/relaton-data-w3c/pull/11 processing failed because some yaml have missing `data` and/or `docstatus` objects in yaml

How to deal with such documents? Should we ignore them from processing?

2023-09-04 05:54 UTC, CAMOBAP commented
> @andrew2net @ronaldtse here and in [relaton/relaton-data-w3c#11](https://github.com/relaton/relaton-data-w3c/pull/11) processing failed because some yaml have missing `data` and/or `docstatus` objects in yaml
> 
> How to deal with such documents? Should we ignore them from processing?

@andrew2net could you please review/approve these changes https://github.com/relaton/jekyll-theme-relaton-data-index/compare/517a44c6c0e3b20eb72eb1b961f1b983b7ae8021...main

2023-09-04 08:28 UTC, ronaldtse commented
@CAMOBAP those changes look fine to me. Next time can you make a PR, so we can track the issue, and then @andrew2net can easily make the release? Thanks!

2023-09-04 10:18 UTC, CAMOBAP commented
> @CAMOBAP those changes look fine to me. Next time can you make a PR, so we can track the issue, and then @andrew2net can easily make the release? Thanks!

For sure, but for now, we use https://github.com/relaton/jekyll-theme-relaton-data-index/ as a repository (i.e. git clone) it even doesn't have Gemfile

@ronaldtse @andrew2net  it's possible to pack jekyll-theme as a gem (including all assets and templates) and reuse it in a such way, right?

2023-09-04 10:21 UTC, ronaldtse commented
> it's possible to pack jekyll-theme as a gem (including all assets and templates) and reuse it in a such way, right?

Yes that's the correct way of doing things.

2023-09-04 10:25 UTC, ronaldtse requested changes

2023-09-04 10:25 UTC, ronaldtse commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
@CAMOBAP let's not use `master` but `main`?

2023-09-04 10:26 UTC, CAMOBAP commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
100%, unfortunately I don't have permission to change the default branch, as far as I see it's changed already so I will update the configuration accordingly

2023-09-04 10:29 UTC, CAMOBAP commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
@ronaldtse to be on the same page I temporally created `master` branch otherwise workflows for whole `relaton` becomes broken, I will delete it back once configuration will be updated across the repositories

2023-09-04 10:45 UTC, ronaldtse commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
@CAMOBAP okay, please let me know which repositories are missing the `main` branch and I can create them. Thanks!

2023-09-04 10:46 UTC, ronaldtse approved these changes

2023-09-04 10:54 UTC, CAMOBAP commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
I mean that other repositories in relation organization are referencing workflows from `support` as `...@master`

But I will prepare list of repos that still have `master` as default branch and report them to separate ticket

2023-09-04 12:28 UTC, ronaldtse commented on .github/workflows/deploy.yml
> +    uses: relaton/support/.github/workflows/data-deploy.yml@master
Got it, thanks! Please assign me.

2023-09-04 14:02 UTC, andrew2net commented
> @andrew2net could you please review/approve these changes [relaton/jekyll-theme-relaton-data-index@517a44c...main](https://github.com/relaton/jekyll-theme-relaton-data-index/compare/517a44c6c0e3b20eb72eb1b961f1b983b7ae8021...main)

LGTM

2023-09-04 16:47 UTC, andrew2net approved these changes

2023-09-04 16:54 UTC, merged